### ISSUE TITLE
P(s) = 1 with no explanation in the probability cheatsheet

### ISSUE THREAD

**Issue by JordanKadish** [shervinea/stanford-cme-106-probability-and-statistics#3]
near the beginning of the pdf, you claim 3 axioms without explaining where the second one came from/mentioning the symbol "S", which I assume is meant to denote sample space

**Comment by shervinea** [comment]
Hi Jordan, thanks for your interest. 

The definition of S is given by the first bullet point of the subsection: 

> Sample space - The set of all possible outcomes [...] is denoted by S.
